import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import conectarDB from '../utils/connectDb'
import User from '../models/models'
import { UserModel } from '../models/models'
import type { NextApiRequest, NextApiResponse } from 'next'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}


export default Home


export async function getServerSideProps(req: NextApiRequest,res: NextApiResponse) {

  try {
    await conectarDB();
    
    // const { params } = req
    // const userM = await User.findOne({email: req.body.email})

    // console.log(userM)
    // const res: UserModel = await User.find({});
    // const res: typeOf User = await User.find({})

    // const user = res.map((doc) => {
    //   const user = doc.toObject();
    //   user._id = `${user._id}`;
    //   return user;
    // });

    // console.log(res)
    return {props: {user : 123}}
    // return { props: { user } };
  } catch (error) {
    console.log(error);
  }
}